"""AFRL/DARPA Project Task 1: UIUC

Given: A grid and a graph

Find: Valid embeddings, and then start with the simplest connections and increase complexity.

Assumptions
1. The field effects are generated by the same components we are embedding

https://networkx.org/documentation/stable/reference/algorithms/shortest_paths.html
https://networkx.org/documentation/stable/reference/algorithms/traversal.html


"""

import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

class Element:
    """
    An element is ...

    """
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z


class Embedding:
    """
    An embedding is ...
    """

    def __init__(self):

        self.sequence = []

class Mesh:
    """
    A mesh is ...
    """
    def __init__(self):
        self.elements = []
        self.edges = []
        self.faces = []
        self.volumes = []

    def add_element(self, element):
        pass

    def add_edge(self, edge):
        pass

    def add_face(self, face):
        pass

    def add_volume(self, volume):
        pass

    def adjacent_elements(self, element):
        pass



    def plot(self):
        pass



